export const legendaryCards = [
  {
    no: 1,
    name: 'Babar Azam',
    country: 'PAK',
    points: 818,
    role: ['Batsman'],
    age: 27,
    battingStyle: 'Right Hand Bat',
    bowlingStyle: '',
  },
  {
    no: 2,
    name: 'Virat Kohli',
    country: 'IND',
    points: 811,
    role: ['Batsman'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 3,
    name: 'Aiden Markram',
    country: 'SA',
    points: 796,
    role: ['Batsman'],
    age: 27,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 4,
    name: 'IMAM-UL-HAQ',
    country: 'PAK',
    points: 795,
    role: ['Batsman'],
    age: 26,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 5,
    name: 'Mohammad Rizwan',
    country: 'PAK',
    points: 794,
    role: ['WK-Batsman'],
    age: 30,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 6,
    name: 'Rohit Sharma',
    country: 'IND',
    points: 791,
    role: ['Batsman'],
    age: 35,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 7,
    name: 'Quinton deKock',
    country: 'SA',
    points: 789,
    role: ['WK-Batsman'],
    age: 29,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 8,
    name: 'Tabraiz Shamsi',
    country: 'SA',
    points: 784,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Left-arm chinaman',
  },
  {
    no: 9,
    name: 'Jonny Bairstow',
    country: 'ENG',
    points: 775,
    role: ['WK-Batsman'],
    age: 32,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 10,
    name: 'David Warner',
    country: 'AUS',
    points: 750,
    role: ['Batsman'],
    age: 35,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 11,
    name: 'Adil Rashid',
    country: 'ENG',
    points: 746,
    role: ['Bowler'],
    age: 34,
    battingStlye: '',
    bowlingStlye: 'Left-arm legbreak',
  },
  {
    no: 12,
    name: 'Joe Root',
    country: 'ENG',
    points: 740,
    role: ['Batsman'],
    age: 31,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 13,
    name: 'Fakhar Zaman',
    country: 'PAK',
    points: 730,
    role: ['Batsman'],
    age: 32,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 14,
    name: 'Dawid Malan',
    country: 'ENG',
    points: 728,
    role: ['Batsman'],
    age: 34,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 15,
    name: 'Trent Boult',
    country: 'NZ',
    points: 726,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast-medium',
  },
  {
    no: 16,
    name: 'Adam Zampa',
    country: 'AUS',
    points: 719,
    role: ['Bowler'],
    age: 30,
    battingStlye: '',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 17,
    name: 'Rashid khan',
    country: 'AFG',
    points: 714,
    role: ['Bowler'],
    age: 23,
    battingStlye: '',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 18,
    name: 'Shai Hope',
    country: 'WI',
    points: 713,
    role: ['WK-Batsman'],
    age: 28,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 19,
    name: 'Devon Conway',
    country: 'NZ',
    points: 703,
    role: ['WK-Batsman'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 20,
    name: 'Shikhar Dhawan',
    country: 'IND',
    points: 701,
    role: ['Batsman'],
    age: 36,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 21,
    name: 'Chris Woakes',
    country: 'ENG',
    points: 700,
    role: ['Bowling', 'Allrounder'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 22,
    name: 'Josh Hazlewood',
    country: 'AUS',
    points: 698,
    role: ['Bowler'],
    age: 31,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 23,
    name: 'Anrich Nortje',
    country: 'SA',
    points: 695,
    role: ['Bowler'],
    age: 28,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 24,
    name: 'Aaron Finch',
    country: 'AUS',
    points: 692,
    role: ['Batsman'],
    age: 35,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 25,
    name: 'Mushfiqur Rahim',
    country: 'BAN',
    points: 691,
    role: ['WK-Batsman'],
    age: 34,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 26,
    name: 'Wanindu Hasaranga',
    country: 'SL',
    points: 687,
    role: ['Bowling', 'Allrounder'],
    age: 24,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 27,
    name: 'Steve Smith',
    country: 'AUS',
    points: 686,
    role: ['Batsman'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 28,
    name: 'Matt Henry',
    country: 'NZ',
    points: 683,
    role: ['Bowler'],
    age: 30,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 29,
    name: 'Mujeeb Ur Rahman',
    country: 'AFG',
    points: 681,
    role: ['Bowler'],
    age: 21,
    battingStlye: '',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 30,
    name: 'Jasprit Bumrah',
    country: 'IND',
    points: 679,
    role: ['Bowler'],
    age: 28,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 31,
    name: 'Shaheen Afridi',
    country: 'PAK',
    points: 671,
    role: ['Bowler'],
    age: 22,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast-medium',
  },
  {
    no: 32,
    name: 'Rassie van der Dussen',
    country: 'SA',
    points: 669,
    role: ['Batsman'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 33,
    name: 'Mehedi Hasan',
    country: 'BAN',
    points: 661,
    role: ['Bowling', 'Allrounder'],
    age: 24,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 34,
    name: 'Glenn Maxwell',
    country: 'AUS',
    points: 664,
    role: ['Batting', 'Allrounder'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
];

export const superRareCards = [
  {
    no: 36,
    name: 'Tamim Iqbal',
    country: 'BAN',
    points: 662,
    role: ['Batsman'],
    age: 33,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 37,
    name: 'Martin Guptill',
    country: 'NZ',
    points: 658,
    role: ['Batsman'],
    age: 35,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 38,
    name: 'Shakib Al Hasan',
    country: 'BAN',
    points: 657,
    role: ['Batting', 'Allrounder'],
    age: 35,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 39,
    name: 'Pathum Nissanka',
    country: 'SL',
    points: 654,
    role: ['Batsman'],
    age: 24,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 40,
    name: 'Alex Carey',
    country: 'AUS',
    points: 651,
    role: ['WK-Batsman'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 41,
    name: 'Ben Stokes',
    country: 'ENG',
    points: 651,
    role: ['Batting', 'Allrounder'],
    age: 31,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 42,
    name: 'Tom Latham',
    country: 'NZ',
    points: 646,
    role: ['WK-Batsman'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 35,
    name: 'Lokesh Rahul',
    country: 'IND',
    points: 640,
    role: ['WK-Batsman'],
    age: 30,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 43,
    name: 'Kagiso Rabada',
    country: 'SA',
    points: 644,
    role: ['Bowler'],
    age: 27,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 44,
    name: 'Mitchell Starc',
    country: 'AUS',
    points: 642,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast',
  },
  {
    no: 45,
    name: 'Nasum Ahmed',
    country: 'BAN',
    points: 637,
    role: ['Bowler'],
    age: 27,
    battingStlye: '',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 46,
    name: 'Hazratullah',
    country: 'AFG',
    points: 633,
    role: ['Batsman'],
    age: 24,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 47,
    name: 'Tim Southee',
    country: 'NZ',
    points: 633,
    role: ['Bowler'],
    age: 33,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 48,
    name: 'Ashton Agar',
    country: 'AUS',
    points: 632,
    role: ['Bowling', 'Allrounder'],
    age: 28,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 49,
    name: 'Nicholas Pooran',
    country: 'WI',
    points: 632,
    role: ['WK-Batsman'],
    age: 26,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 50,
    name: 'David Miller',
    country: 'SA',
    points: 630,
    role: ['Batsman'],
    age: 32,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 51,
    name: 'Pat Cummins',
    country: 'AUS',
    points: 627,
    role: ['Bowler'],
    age: 29,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 52,
    name: 'Mahedi Hasan',
    country: 'BAN',
    points: 622,
    role: ['Batting', 'Allrounder'],
    age: 27,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 53,
    name: 'Shadab Khan',
    country: 'PAK',
    points: 621,
    role: ['Bowling', 'Allrounder'],
    age: 23,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 54,
    name: 'Mustafizur Rahman',
    country: 'BAN',
    points: 614,
    role: ['Bowler'],
    age: 26,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast-medium',
  },
  {
    no: 55,
    name: 'Yuzvendra Chahal',
    country: 'IND',
    points: 610,
    role: ['Bowler'],
    age: 31,
    battingStlye: '',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 56,
    name: 'Jos Buttler',
    country: 'ENG',
    points: 609,
    role: ['WK-Batsman'],
    age: 31,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 57,
    name: 'Lungi Ngidi',
    country: 'SA',
    points: 607,
    role: ['Bowler'],
    age: 26,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 58,
    name: 'Litton Das',
    country: 'BAN',
    points: 602,
    role: ['WK-Batsman'],
    age: 27,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 59,
    name: 'Jason Roy',
    country: 'ENG',
    points: 602,
    role: ['Batsman'],
    age: 31,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 60,
    name: 'Shreyas Iyer',
    country: 'IND',
    points: 600,
    role: ['Batsman'],
    age: 27,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 61,
    name: 'Mitchell Santner',
    country: 'NZ',
    points: 600,
    role: ['Bowling', 'Allrounder'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 62,
    name: 'Akeal Hosein',
    country: 'WI',
    points: 598,
    role: ['Bowler'],
    age: 29,
    battingStlye: '',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 63,
    name: 'Mark Wood',
    country: 'ENG',
    points: 594,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 64,
    name: 'Alzarri Joseph',
    country: 'WI',
    points: 593,
    role: ['Bowler'],
    age: 25,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 65,
    name: 'Rahmat Shah',
    country: 'AFG',
    points: 593,
    role: ['Batting', 'Allrounder'],
    age: 28,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 66,
    name: 'Shimron Hetmyer',
    country: 'WI',
    points: 589,
    role: ['Batsman'],
    age: 25,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 67,
    name: 'Bhuvneshwar Kumar',
    country: 'IND',
    points: 586,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 68,
    name: 'Haris Sohail',
    country: 'PAK',
    points: 585,
    role: ['Batting', 'Allrounder'],
    age: 33,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Left-arm orthodox',
  },
  {
    no: 69,
    name: 'Ish Sodhi',
    country: 'NZ',
    points: 584,
    role: ['Bowler'],
    age: 29,
    battingStlye: '',
    bowlingStlye: 'Right-arm legbreak',
  },
  {
    no: 70,
    name: 'Travis Head',
    country: 'AUS',
    points: 581,
    role: ['Batting', 'Allrounder'],
    age: 28,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 71,
    name: 'Janneman Malan',
    country: 'SA',
    points: 574,
    role: ['Batsman'],
    age: 26,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 72,
    name: 'Akila Dananjaya',
    country: 'SL',
    points: 574,
    role: ['Bowler'],
    age: 28,
    battingStlye: '',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 73,
    name: 'Henry Nicholls',
    country: 'NZ',
    points: 571,
    role: ['Batsman'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 74,
    name: 'Chris Jordan',
    country: 'ENG',
    points: 566,
    role: ['Bowler'],
    age: 33,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 75,
    name: 'Avishka Fernando',
    country: 'SL',
    points: 560,
    role: ['Batsman'],
    age: 24,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 76,
    name: 'Maheesh Theekshana',
    country: 'SL',
    points: 557,
    role: ['Bowler'],
    age: 21,
    battingStlye: '',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 77,
    name: 'Mitchell Marsh',
    country: 'AUS',
    points: 552,
    role: ['Batting', 'Allrounder'],
    age: 30,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 78,
    name: 'Jason Holder',
    country: 'WI',
    points: 550,
    role: ['Bowling', 'Allrounder'],
    age: 30,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 79,
    name: 'Mohammed Shami',
    country: 'IND',
    points: 549,
    role: ['Bowler'],
    age: 31,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 80,
    name: 'Najibullah Zadran',
    country: 'AFG',
    points: 547,
    role: ['Batsman'],
    age: 29,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 81,
    name: 'Reeza Hendricks',
    country: 'SA',
    points: 547,
    role: ['Batsman'],
    age: 32,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 82,
    name: 'Eoin Morgan',
    country: 'ENG',
    points: 547,
    role: ['Batsman'],
    age: 35,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 83,
    name: 'charith-asalanka',
    country: 'SL',
    points: 546,
    role: ['Bowling', 'Allrounder'],
    age: 24,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 84,
    name: 'Haris Rauf',
    country: 'PAK',
    points: 545,
    role: ['Bowler'],
    age: 28,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 85,
    name: 'Kusal Perera',
    country: 'SL',
    points: 543,
    role: ['WK-Batsman'],
    age: 31,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 86,
    name: 'Dushmantha Chameera',
    country: 'SL',
    points: 543,
    role: ['Bowler'],
    age: 30,
    battingStlye: '',
    bowlingStlye: 'Right-arm fast',
  },
  {
    no: 87,
    name: 'Rahmanullah Gurbaz',
    country: 'AFG',
    points: 538,
    role: ['WK-Batsman'],
    age: 20,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 88,
    name: 'Kuldeep Yadav',
    country: 'IND',
    points: 538,
    role: ['Bowler'],
    age: 27,
    battingStlye: '',
    bowlingStlye: 'Left-arm chinaman',
  },
  {
    no: 89,
    name: 'Mohammad Naim',
    country: 'BAN',
    points: 536,
    role: ['Batsman'],
    age: 22,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 90,
    name: 'Angelo Mathews',
    country: 'SL',
    points: 534,
    role: ['Batting', 'Allrounder'],
    age: 35,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 91,
    name: 'Suryakumar Yadav',
    country: 'IND',
    points: 530,
    role: ['Batsman'],
    age: 31,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 92,
    name: 'Dwaine Pretorius',
    country: 'SA',
    points: 525,
    role: ['Bowling', 'Allrounder'],
    age: 33,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: 'Right-arm fast-medium',
  },
  {
    no: 93,
    name: 'Evin Lewis',
    country: 'WI',
    points: 524,
    role: ['Batsman'],
    age: 30,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 94,
    name: 'Danushka Gunathilaka',
    country: 'SL',
    points: 522,
    role: ['Batting', 'Allrounder'],
    age: 31,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: 'Right-arm offbreak',
  },
  {
    no: 95,
    name: 'Sheldon Cottrell',
    country: 'WI',
    points: 514,
    role: ['Bowler'],
    age: 32,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast-medium',
  },
  {
    no: 96,
    name: 'Hashmatullah Shahidi',
    country: 'AFG',
    points: 512,
    role: ['Batsman'],
    age: 27,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 97,
    name: 'Kusal Mendis',
    country: 'SL',
    points: 511,
    role: ['Batsman'],
    age: 27,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 98,
    name: 'Glenn Phillips',
    country: 'NZ',
    points: 510,
    role: ['WK-Batsman'],
    age: 25,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 99,
    name: 'Soumya Sarkar',
    country: 'BAN',
    points: 506,
    role: ['Batsman'],
    age: 29,
    battingStlye: 'Left Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 100,
    name: 'Mohammad Shoriful Islam',
    country: 'BAN',
    points: 505,
    role: ['Bowler'],
    age: 21,
    battingStlye: '',
    bowlingStlye: 'Left-arm fast-medium',
  },
  {
    no: 101,
    name: 'Temba Bavuma',
    country: 'SA',
    points: 502,
    role: ['Batsman'],
    age: 32,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
  {
    no: 102,
    name: 'Sarfaraz Ahmed',
    country: 'PAK',
    points: 497,
    role: ['WK-Batsman'],
    age: 35,
    battingStlye: 'Right Handed Bat',
    bowlingStlye: '',
  },
];

export const rareCards = [
  {
    no: 103,
    name: 'Lahiru Kumara',
    country: 'SL',
    points: 493,
    roles: ['Lahiru Kumara'],
    age: '25',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 104,
    name: 'Kane Williamson',
    country: 'NZ',
    points: 483,
    roles: ['Batsman'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 105,
    name: 'Prasidh Krishna',
    country: 'IND',
    points: 481,
    roles: ['Bowler'],
    age: '26',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 106,
    name: 'Kane Richardson',
    country: 'AUS',
    points: 476,
    roles: ['Bowler'],
    age: '31',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 107,
    name: 'Deepak Chahar',
    country: 'IND',
    points: 472,
    roles: ['Bowler'],
    age: '29',
    battingStyle: '',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 108,
    name: 'Fabian Allen',
    country: 'WI',
    points: 455,
    roles: ['Batting', 'Allrounder'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 109,
    name: 'Nuwan Pradeep',
    country: 'SL',
    points: 455,
    roles: ['Bowler'],
    age: '35',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 110,
    name: 'Rovman Powell',
    country: 'WI',
    points: 452,
    roles: ['Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 111,
    name: 'Keshav Maharaj',
    country: 'SA',
    points: 451,
    roles: ['Bowler'],
    age: '32',
    battingStyle: '',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 112,
    name: 'Josh Inglis',
    country: 'AUS',
    points: 450,
    roles: ['WK-Batsman'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 113,
    name: 'George Linde',
    country: 'SA',
    points: 446,
    roles: ['Batting', 'Allrounder'],
    age: '30',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 114,
    name: 'Mohammad Nawaz',
    country: 'PAK',
    points: 442,
    roles: ['Bowling', 'Allrounder'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 115,
    name: 'Tim Seifert',
    country: 'NZ',
    points: 441,
    roles: ['WK-Batsman'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 116,
    name: 'Lachlan Ferguson',
    country: 'NZ',
    points: 440,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 117,
    name: 'Hasan Ali',
    country: 'PAK',
    points: 439,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 118,
    name: 'Chamika Karunaratne',
    country: 'SL',
    points: 439,
    roles: ['Bowler'],
    age: '26',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 119,
    name: 'Faheem Ashraf',
    country: 'PAK',
    points: 438,
    roles: ['Bowling', 'Allrounder'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 120,
    name: 'Tom Curran',
    country: 'ENG',
    points: 436,
    roles: ['Bowling', 'Allrounder'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 121,
    name: 'Bjorn Fortuin',
    country: 'SA',
    points: 434,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 122,
    name: 'Mohammad Wasim',
    country: 'PAK',
    points: 432,
    roles: ['Bowling', 'Allrounder'],
    age: '20',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 123,
    name: 'Suranga Lakmal',
    country: 'SL',
    points: 429,
    roles: ['Bowler'],
    age: '35',
    battingStyle: '',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 124,
    name: 'Rishabh Pant',
    country: 'IND',
    points: 429,
    roles: ['WK-Batsman'],
    age: '24',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 125,
    name: 'Washington Sundar',
    country: 'IND',
    points: 423,
    roles: ['Batting', 'Allrounder'],
    age: '22',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 126,
    name: 'Hayden Walsh',
    country: 'WI',
    points: 415,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 127,
    name: 'Brandon King',
    country: 'WI',
    points: 408,
    roles: ['Batsman'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 128,
    name: 'Matthew Wade',
    country: 'AUS',
    points: 407,
    roles: ['WK-Batsman'],
    age: '34',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 129,
    name: 'Taskin Ahmed',
    country: 'BAN',
    points: 407,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 130,
    name: 'Shardul Thakur',
    country: 'IND',
    points: 403,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 131,
    name: 'Ishan Kishan',
    country: 'IND',
    points: 401,
    roles: ['WK-Batsman'],
    age: '23',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 132,
    name: 'Jason Behrendorff',
    country: 'AUS',
    points: 400,
    roles: ['Bowler'],
    age: '32',
    battingStyle: '',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 133,
    name: 'Usman Ghani',
    country: 'AFG',
    points: 397,
    roles: ['Batsman'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 134,
    name: 'Doug Bracewell',
    country: 'NZ',
    points: 396,
    roles: ['Bowler'],
    age: '31',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 135,
    name: 'Wayne Parnell',
    country: 'SA',
    points: 392,
    roles: ['Bowling', 'Allrounder'],
    age: '32',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 136,
    name: 'Rubel Hossain',
    country: 'BAN',
    points: 388,
    roles: ['Bowler'],
    age: '32',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 137,
    name: 'Daryl Mitchell',
    country: 'NZ',
    points: 384,
    roles: ['Bowling', 'Allrounder'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm medium',
  },
  {
    no: 138,
    name: 'Ravichandran Ashwin',
    country: 'IND',
    points: 381,
    roles: ['Bowling', 'Allrounder'],
    age: '35',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 139,
    name: 'Jeffrey Vandersay',
    country: 'SL',
    points: 365,
    roles: ['Bowler'],
    age: '32',
    battingStyle: '',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 140,
    name: 'Lakshan Sandakan',
    country: 'SL',
    points: 365,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Left-arm chinaman',
  },
  {
    no: 141,
    name: 'Mohammad Nabi',
    country: 'AFG',
    points: 276,
    roles: ['Bowling', 'Allrounder'],
    age: '37',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 142,
    name: 'Colin de Grandhomme',
    country: 'NZ',
    points: 262,
    roles: ['Batting', 'Allrounder'],
    age: '35',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 143,
    name: 'Imad Wasim',
    country: 'PAK',
    points: 248,
    roles: ['All-Rounder'],
    age: '33',
    battingStyle: 'Left-handed',
    bowlingStyle: 'Slow left-arm orthodox',
  },
  {
    no: 144,
    name: 'Jimmy Neesham',
    country: 'NZ',
    points: 220,
    roles: ['Batting', 'Allrounder'],
    age: '31',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 145,
    name: 'Moeen Ali',
    country: 'ENG',
    points: 205,
    roles: ['Bowling', 'Allrounder'],
    age: '33',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm offbreak',
  },
  {
    no: 146,
    name: 'Hardik Pandya',
    country: 'India',
    points: 203,
    roles: ['Batting', 'Allrounder'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 147,
    name: 'Marcus Stoinis',
    country: 'Aus',
    points: 197,
    roles: ['Batting', 'Allrounder'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 148,
    name: 'Andile Phehlukwayo',
    country: 'SA',
    points: 195,
    roles: ['Bowling', 'Allrounder'],
    age: '26',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 149,
    name: 'Dhananjaya de Silva',
    country: 'SL',
    points: 184,
    roles: ['Batting', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 150,
    name: 'Mohammad  Saifuddin',
    country: 'BAN',
    points: 171,
    roles: ['Bowling', 'Allrounder'],
    age: '25',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 151,
    name: 'Roston Chase',
    country: 'WI',
    points: 119,
    roles: ['Bowling', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 152,
    name: 'Mahmudullah',
    country: 'BAN',
    points: 108,
    roles: ['Batting', 'Allrounder'],
    age: '36',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 153,
    name: 'Dasun Shanaka',
    country: 'SL',
    points: 105,
    roles: ['Batting', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 154,
    name: 'Karim Janat',
    country: 'AFG',
    points: 99,
    roles: ['Bowler'],
    age: '23',
    battingStyle: '',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 155,
    name: 'Mosaddek Hossain',
    country: 'BAN',
    points: 95,
    roles: ['Batting', 'Allrounder'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 156,
    name: 'Gulbadin Naib',
    country: 'AFG',
    points: 83,
    roles: ['Bowling', 'Allrounder'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 157,
    name: 'Andre Russell',
    country: 'WI',
    points: 62,
    roles: ['Bowling', 'Allrounder'],
    age: '34',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 158,
    name: 'Afif Hossain',
    country: 'BAN',
    points: 58,
    roles: ['Batting', 'Allrounder'],
    age: '22',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 159,
    name: 'Luke Bichard',
    country: 'WI',
    points: 54,
    roles: ['WK-Batsman'],
    age: '19',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 160,
    name: 'Sam Curran',
    country: 'ENG',
    points: 35,
    roles: ['Bowling', 'Allrounder'],
    age: '24',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 161,
    name: 'Lockie Ferguson',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 162,
    name: 'Usman Khawaja',
    country: 'AUS',
    points: 0,
    roles: ['Batsman'],
    age: '35',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 163,
    name: 'Kyle Jamieson',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 164,
    name: 'Marnus Labuschagne',
    country: 'AUS',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 165,
    name: 'Jofra Archer',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 166,
    name: 'Dean Elgar',
    country: 'SA',
    points: 0,
    roles: ['Batsman'],
    age: '34',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 167,
    name: 'Dinesh Chandimal',
    country: 'SL',
    points: 0,
    roles: ['WK-Batsman'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 168,
    name: 'Rangana Herath',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '44',
    battingStyle: '',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 169,
    name: 'Darren Bravo',
    country: 'WI',
    points: 0,
    roles: ['Batsman'],
    age: '33',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 170,
    name: 'Sunil Narine',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '34',
    battingStyle: '',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 171,
    name: 'Sam Billings',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 172,
    name: 'Ajinkya Rahane',
    country: 'Ind',
    points: 0,
    roles: ['Batsman'],
    age: '33',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 173,
    name: 'Cheteshwar Pujara',
    country: 'ind',
    points: 0,
    roles: ['Batsman'],
    age: '34',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 174,
    name: 'Ishant Sharma',
    country: 'ind',
    points: 0,
    roles: ['Bowler'],
    age: '33',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 175,
    name: 'Umesh Yadav',
    country: 'ind',
    points: 0,
    roles: ['Bowler'],
    age: '34',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 176,
    name: 'Ollie Pope',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 177,
    name: 'Rory Burns',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '31',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 178,
    name: 'Zak Crawley',
    country: 'ENG',
    points: 0,
    roles: ['Batsman'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 179,
    name: 'Asif Ali',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 180,
    name: 'Azhar Ali',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '37',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 181,
    name: 'Asghar Afghan',
    country: 'AFN',
    points: 0,
    roles: ['Batsman'],
    age: '34',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 182,
    name: 'Sanju Samson',
    country: 'IND',
    points: 0,
    roles: ['WK-Batsman'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 183,
    name: 'Mayank Agarwal',
    country: 'IND',
    points: 0,
    roles: ['Batsman'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 184,
    name: 'Stuart Broad',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '35',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 185,
    name: 'Harshal Patel',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '31',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 186,
    name: 'Mohammed Siraj',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 187,
    name: 'Sean Abbott',
    country: 'AUS',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 188,
    name: 'Ruturaj Gaikwad',
    country: 'IND',
    points: 0,
    roles: ['Batsman'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 189,
    name: 'Avesh Khan',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 190,
    name: 'James Anderson',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '39',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 191,
    name: 'Alex Lees',
    country: 'ENG',
    points: 0,
    roles: ['Batsman'],
    age: '29',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 192,
    name: 'Ben Foakes',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 193,
    name: 'Craig Overton',
    country: 'ENG',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '28',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 194,
    name: 'Dan Lawrence',
    country: 'ENG',
    points: 0,
    roles: ['Batsman'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 195,
    name: 'George Garton',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: '',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 196,
    name: 'Harry Brook',
    country: 'ENG',
    points: 0,
    roles: ['Batsman'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 197,
    name: 'Haseeb Hameed',
    country: 'ENG',
    points: 0,
    roles: ['Batsman'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 198,
    name: 'Jack Leach',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: '',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 199,
    name: 'Liam Dawson',
    country: 'ENG',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 200,
    name: 'Matt Parkinson',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: '',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 201,
    name: 'Matthew Fisher',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '24',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 202,
    name: 'Ollie Robinson',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 203,
    name: 'Philip Salt',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 204,
    name: 'Reece Topley',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: '',
    bowlingStyle: 'Left-arm fast-medium',
  },
];

export const commonCards = [
  {
    no: 205,
    name: 'Saqib Mahmood',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 206,
    name: 'Tom Banton',
    country: 'ENG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 207,
    name: 'Tymal Mills',
    country: 'ENG',
    points: 0,
    roles: ['Bowler'],
    age: '29',
    battingStyle: '',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 208,
    name: 'Axar Patel',
    country: 'IND',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 209,
    name: 'Deepak Hooda',
    country: 'IND',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 210,
    name: 'Hanuma Vihari',
    country: 'IND',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '28',
    battingStyle: 'Right Handed Ba',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 211,
    name: 'Jayant Yadav',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '32',
    battingStyle: '',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 212,
    name: 'Priyank Panchal',
    country: 'IND',
    points: 0,
    roles: ['Batsman'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 213,
    name: 'Ravi Bishnoi',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 214,
    name: 'Saurabh Kumar',
    country: 'IND',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '29',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 215,
    name: 'Srikar Bharat',
    country: 'IND',
    points: 0,
    roles: ['WK-Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 216,
    name: 'Venkatesh Iyer',
    country: 'IND',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '27',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 217,
    name: 'Wriddhiman Saha',
    country: 'IND',
    points: 0,
    roles: ['WK-Batsman'],
    age: '37',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 218,
    name: 'Krunal Pandya',
    country: 'IND',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '31',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 219,
    name: 'Ben Dwarshuis',
    country: 'AUS',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 220,
    name: 'Ben McDermott',
    country: 'AUS',
    points: 0,
    roles: ['WK-Batsman'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 221,
    name: 'Cameron Green',
    country: 'AUS',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 222,
    name: 'Daniel Sams',
    country: 'AUS',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 223,
    name: 'Jhye Richardson',
    country: 'AUS',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 224,
    name: 'Marcus Harris',
    country: 'AUS',
    points: 0,
    roles: ['Batsman'],
    age: '29',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 225,
    name: 'Matt Renshaw',
    country: 'AUS',
    points: 0,
    roles: ['Batsman'],
    age: '26',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 226,
    name: 'Michael Neser',
    country: 'AUS',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 227,
    name: 'Mitchell Swepson',
    country: 'AUS',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 228,
    name: 'Nathan Ellis',
    country: 'AUS',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 229,
    name: 'Scott Boland',
    country: 'AUS',
    points: 0,
    roles: ['Bowler'],
    age: '33',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 230,
    name: 'Abu Jayed',
    country: 'BAN',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: '',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 231,
    name: 'Aminul Islam',
    country: 'BAN',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 232,
    name: 'Ebadot Hossain',
    country: 'BAN',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 233,
    name: 'Khaled Ahmed',
    country: 'BAN',
    points: 0,
    roles: ['Bowler'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 234,
    name: 'Mahmudul Hasan Joy',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 235,
    name: 'Mominul Haque',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '30',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 236,
    name: 'Munim Shahriar',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 237,
    name: 'Najmul Hossain Shanto',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '23',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 238,
    name: 'Nurul Hasan',
    country: 'BAN',
    points: 0,
    roles: ['WK-Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 239,
    name: 'Saif Hassan',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 240,
    name: 'Shadman Islam',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '27',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 241,
    name: 'Shamim Hossain',
    country: 'BAN',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '21',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 242,
    name: 'Shohidul Islam',
    country: 'BAN',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 243,
    name: 'Taijul Islam',
    country: 'BAN',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 244,
    name: 'Yasir Ali',
    country: 'BAN',
    points: 0,
    roles: ['Batsman'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 245,
    name: 'Adam Milne',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 246,
    name: 'Ben Sears',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 247,
    name: 'Blair Tickner',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 248,
    name: 'Cole McConchie',
    country: 'NZ',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 249,
    name: 'Finn Allen',
    country: 'NZ',
    points: 0,
    roles: ['WK-Batsman'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 250,
    name: 'George Worker',
    country: 'NZ',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '32',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 251,
    name: 'Jacob Duffy',
    country: 'NZ',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 252,
    name: 'Mark Chapman',
    country: 'NZ',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '27',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 253,
    name: 'Michael Bracewell',
    country: 'NZ',
    points: 0,
    roles: ['WK-Batsman'],
    age: '31',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 254,
    name: 'Neil Wagner',
    country: 'NZ',
    points: 0,
    roles: ['Bowler'],
    age: '36',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 255,
    name: 'Rachin Ravindra',
    country: 'NZ',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '22',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 256,
    name: 'Scott Kuggeleijn',
    country: 'NZ',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 257,
    name: 'Tom Blundell',
    country: 'NZ',
    points: 0,
    roles: ['WK-Batsman'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 258,
    name: 'Will Young',
    country: 'NZ',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 259,
    name: 'Abdullah Shafique',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 260,
    name: 'Abid Ali',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '34',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 261,
    name: 'Haider Ali',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 262,
    name: 'Iftikhar Ahmed',
    country: 'PAK',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 263,
    name: 'Khushdil Shah',
    country: 'PAK',
    points: 0,
    roles: ['Batsman'],
    age: '27',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 264,
    name: 'Mohammad Haris',
    country: 'PAK',
    points: 0,
    roles: ['WK-Batsman'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 265,
    name: 'Mohammad Hasnain',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 266,
    name: 'Naseem Shah',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '19',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 267,
    name: 'Nauman Ali',
    country: 'PAK',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '35',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 268,
    name: 'Sajid Khan',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-arm off break',
  },
  {
    no: 269,
    name: 'Saud Shakeel',
    country: 'PAK',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '26',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 270,
    name: 'Shahnawaz Dahani',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 271,
    name: 'Usman Qadir',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 272,
    name: 'Zahid Mahmood',
    country: 'PAK',
    points: 0,
    roles: ['Bowler'],
    age: '34',
    battingStyle: '',
    bowlingStyle: 'Leg break',
  },
  {
    no: 273,
    name: 'Daryn Dupavillon',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 274,
    name: 'Duanne Olivier',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 275,
    name: 'Glenton Stuurman',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 276,
    name: 'Keegan Petersen',
    country: 'SA',
    points: 0,
    roles: ['Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 277,
    name: 'Khaya Zondo',
    country: 'SA',
    points: 0,
    roles: ['Batsman'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 278,
    name: 'Kyle Verreynne',
    country: 'SA',
    points: 0,
    roles: ['WK-Batsman'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 279,
    name: 'Lizaad Williams',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 280,
    name: 'Lutho Sipamla',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 281,
    name: 'Marco Jansen',
    country: 'SA',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm fast',
  },
  {
    no: 282,
    name: 'Ryan Rickelton',
    country: 'SA',
    points: 0,
    roles: ['WK-Batsman'],
    age: '25',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 283,
    name: 'Sarel Erwee',
    country: 'SA',
    points: 0,
    roles: ['Batsman'],
    age: '32',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 284,
    name: 'Simon Harmer',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '33',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 285,
    name: 'Sisanda Magala',
    country: 'SA',
    points: 0,
    roles: ['Bowler'],
    age: '31',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 286,
    name: 'Wiaan Mulder',
    country: 'SA',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 287,
    name: 'Zubayr Hamza',
    country: 'SA',
    points: 0,
    roles: ['Batsman'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 288,
    name: 'Bhanuka Rajapaksa',
    country: 'SL',
    points: 0,
    roles: ['WK-Batsman'],
    age: '30',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 289,
    name: 'Chamika Gunasekara',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 290,
    name: 'Charith Asalanka',
    country: 'SL',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '24',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 291,
    name: 'Janith Liyanage',
    country: 'SL',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 292,
    name: 'Kamil Mishara',
    country: 'SL',
    points: 0,
    roles: ['WK-Batsman'],
    age: '21',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 293,
    name: 'Kamindu Mendis',
    country: 'SL',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '23',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 294,
    name: 'Lahiru Thirimanne',
    country: 'SL',
    points: 0,
    roles: ['Batsman'],
    age: '32',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 295,
    name: 'Lasith Embuldeniya',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 296,
    name: 'Niroshan Dickwella',
    country: 'SL',
    points: 0,
    roles: ['WK-Batsman'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 297,
    name: 'Nuwan Thushara',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 298,
    name: 'Oshada Fernando',
    country: 'SL',
    points: 0,
    roles: ['Batsman'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 299,
    name: 'Praveen Jayawickrama',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 300,
    name: 'Ramesh Mendis',
    country: 'SL',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 301,
    name: 'Vishwa Fernando',
    country: 'SL',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 302,
    name: 'Anderson Phillip',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 303,
    name: 'Devon Thomas',
    country: 'WI',
    points: 0,
    roles: ['WK-Batsman'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 304,
    name: 'Dominic Drakes',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '24',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 305,
    name: 'Gudakesh Motie',
    country: 'WI',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '27',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 306,
    name: 'Jayden Seales',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '20',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 307,
    name: 'Jermaine Blackwood',
    country: 'WI',
    points: 0,
    roles: ['Batsman'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 308,
    name: 'John Campbell',
    country: 'WI',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '28',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 309,
    name: 'Joshua Da Silva',
    country: 'WI',
    points: 0,
    roles: ['WK-Batsman'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 310,
    name: 'Justin Greaves',
    country: 'WI',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 311,
    name: 'Kraigg Brathwaite',
    country: 'WI',
    points: 0,
    roles: ['Batsman'],
    age: '29',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 312,
    name: 'Kyle Mayers',
    country: 'WI',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '29',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 313,
    name: 'Nkrumah Bonner',
    country: 'WI',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '33',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 314,
    name: 'Odean Smith',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 315,
    name: 'Oshane Thomas',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '25',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 316,
    name: 'Romario Shepherd',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 317,
    name: 'Shamarh Brooks',
    country: 'WI',
    points: 0,
    roles: ['Batsman'],
    age: '33',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 318,
    name: 'Veerasammy Permaul',
    country: 'WI',
    points: 0,
    roles: ['Bowler'],
    age: '32',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 319,
    name: 'Abdul Malik',
    country: 'AFG',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '24',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 320,
    name: 'Abdul Wasi',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '19',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 321,
    name: 'Afsar Zazai',
    country: 'AFG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 322,
    name: 'Amir Hamza',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 323,
    name: 'Azmatullah Omarzai',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 324,
    name: 'Darwish Rasooli',
    country: 'AFG',
    points: 0,
    roles: ['Batsman'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 325,
    name: 'Fareed Ahmad',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '27',
    battingStyle: '',
    bowlingStyle: 'Left arm fast medium',
  },
  {
    no: 326,
    name: 'Fazalhaq Farooqi',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left-arm fast-medium',
  },
  {
    no: 327,
    name: 'Hazratullah Zazai',
    country: 'AFG',
    points: 0,
    roles: ['Batsman'],
    age: '24',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm orthodox',
  },
  {
    no: 328,
    name: 'Ibrahim Zadran',
    country: 'AFG',
    points: 0,
    roles: ['Batsman'],
    age: '20',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 329,
    name: 'Javed Ahmadi',
    country: 'AFG',
    points: 0,
    roles: ['Batting', 'Allrounder'],
    age: '30',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
  },
  {
    no: 330,
    name: 'Munir Ahmad',
    country: 'AFG',
    points: 0,
    roles: ['WK-Batsman'],
    age: '26',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 331,
    name: 'Nasir Jamal',
    country: 'AFG',
    points: 0,
    roles: ['Batsman'],
    age: '28',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 332,
    name: 'Naveen-ul-Haq',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '22',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast-medium',
  },
  {
    no: 333,
    name: 'Nijat Masood',
    country: 'AFG',
    points: 0,
    roles: ['Bowling', 'Allrounder'],
    age: '23',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 334,
    name: 'Qais Ahmad',
    country: 'AFG',
    points: 0,
    roles: ['Bowler'],
    age: '21',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm legbreak',
  },
  {
    no: 335,
    name: 'Mohsin Khan',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '23',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm medium-fast',
  },
  {
    no: 336,
    name: 'Abhishek Sharma',
    country: 'IND',
    points: 0,
    roles: ['Batsman'],
    age: '21',
    battingStyle: 'Right-Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 337,
    name: 'Dewald Brevis',
    country: 'SA',
    points: 0,
    roles: [' All-Rounder'],
    age: '19',
    battingStyle: 'Right-Handed Bat',
    bowlingStyle: 'Right-Arm Leg Spin Bowler',
  },
  {
    no: 338,
    name: 'Arshdeep Singh',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '23',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left-arm medium-fast',
  },
  {
    no: 339,
    name: 'Umran Malik',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '22',
    battingStyle: 'Right-Handed Bat',
    bowlingStyle: 'Right-arm fast',
  },
  {
    no: 340,
    name: 'Rahul Tripathi',
    country: 'IND',
    points: 0,
    roles: ['Bowler'],
    age: '29',
    battingStyle: '',
    bowlingStyle: 'Slow left-arm orthodox',
  },
  {
    no: 341,
    name: 'Colin Munro',
    country: 'NZ',
    points: 0,
    roles: ['Batsman'],
    age: '35',
    battingStyle: 'Left-handed',
    bowlingStyle: 'Right-arm medium',
  },
  {
    no: 342,
    name: 'Chris Lynn',
    country: 'AUS',
    points: 0,
    roles: ['Batsman'],
    age: '32',
    battingStyle: 'Right-Handed Bat',
    bowlingStyle: '',
  },
  {
    no: 343,
    name: 'Devdutt Padikkal',
    country: 'IND',
    points: 0,
    roles: ['Batsman'],
    age: '21',
    battingStyle: 'Right-Handed Bat',
    bowlingStyle: 'Right arm offbreak',
  },
];
